// https://www.jenkins.io/doc/book/pipeline/syntax/#environment
// https://www.jenkins.io/doc/pipeline/steps/workflow-basic-steps/#pipeline-basic-steps
// Локальная информация: https://[JENKINS URL]/jenkins/pipeline-syntax/globals
pipeline {
  agent any
  options {
    skipDefaultCheckout(true)
  }
  stages {
    stage('Подготовка'){
      steps{
        script {
          env.HOST_WORKSPACE=env.WORKSPACE.replace(env.JENKINS_HOME,env.JENKINS_HOME_HOST_PATH)
        }
      }
    }
    stage('Поштучные пакеты') {
      matrix {
        axes {
          axis {
              name 'PLATFORM'
              values 'amd64'
          }
          axis {
              name 'APP'
              values 'k9s', 'qbittorrent'
          }
        }
        stages {
          stage('Качат') {
            steps {
              echo 'Скачат'
              sh "echo 1 $PLATFORM $APP"
              sh 'echo 2 $PLATFORM $APP'
              sh '''
cat <<EOF
xxx $PLATFORM $APP yyy
EOF'''
            }
          }
        }
      }
    }
    stage('Мета-пакет') {
      steps {
        echo 'Сделали мета-пакет'
      }
    }
  }
  post {
    always {
      archiveArtifacts artifacts: '**/*.deb'
    }
  }
}