---
all:
  vars:
    ansible_user: "{{secrets.ansible_user}}"
    ansible_password: "{{secrets.ansible_password}}"
    ansible_become_password: "{{secrets.ansible_become_password}}"
  hosts:
    d:
      purpose: desktop
      ansible_connection: local
      ansible_user: "{{secrets.local_user}}"
    atom.local:
      purpose: server
    tw89.local:
      purpose: server
    a1.local:
      purpose: server
    redmi4-p:
      ansible_port: 8022
