---
all:
  vars:
    ansible_user: "{{secrets.ansible_user}}"
    ansible_password: "{{secrets.ansible_password}}"
    ansible_become_password: "{{secrets.ansible_become_password}}"
  children:
    vbox:
      vars:
      hosts:
        alpine-1.local:
          ansible_user: root
    home:
      children:
        debian:
          hosts:
            d:
              ansible_connection: local
            dn2800mt:
            tw89:
              ansible_user: root
        alpine:
          hosts:
            a1.local:
        linux:
          children:
            debian:
            alpine:
