---
all:
  vars:
    ansible_user: "{{secrets.ansible_user}}"
    ansible_password: "{{secrets.ansible_password}}"
    ansible_become_password: "{{secrets.ansible_become_password}}"
  hosts:
    d:
      purpose: desktop
      ansible_connection: local
    atom.local:
      purpose: server
    tw89.local:
      purpose: server
      ansible_become_method: su
    a1.local:
      purpose: server
    redmi4-android6:
      ansible_port: 8022
