---
- name: Настройка домашних линуксов
  hosts: all
  gather_facts: true
  tasks:
# Первичная настройка, когда компьютер только засетаплен: есть ip, есть sshd,
# есть что-то из sudo/su/doas - включает в себя:
# - установку avahi для публикации hostname по mdns;
# - настроку некоторых конфигов.
  - name: Базовая настройка по ip/ssh
    block:
    - when: ansible_facts.distribution == "Debian"
      become: true
      block:
      - copy:
          content: |
            APT::Install-Recommends "0";
            APT::Install-Suggests "0";
          dest: /etc/apt/apt.conf
      - apt:
          name:
          - avahi-daemon
          - bash-completion
          - ca-certificates # нужно докеру и вообще
          - curl # нужно докеру и вообще
          - git
          - gnupg # нужно докеру и вообще
          - jq
      - systemd:
          name: avahi-daemon
          enabled: true
          state: started
    - when: ansible_facts.distribution == "Alpine"
      become: true
      block:
      - apk:
          name:
          - avahi
          - curl
          - grep
          - sed
          - procps
      - service:
          name: "{{item}}"
          enabled: true
          state: started
        loop:
        - avahi-daemon
    - name: Общее для всех-всех-всех
      block:
      - name: Всем ~/.tmux.conf
        include_role:
          name: upload_or_symlink
        vars:
          src: ~/dotfiles/tmux/tmux.conf.3.3
          dest: ~/.tmux.conf
# После того как базовая настройка произведена и компьютер доступен по hostname
# через mdns компьютер добавляется в inventory (hosts.yml) и ему выставляется
# назначение (server, desktop) и в этой секции это назначение настраивается.
    - name: Настройка в зависимости от роли
      block:
      - when: purpose == "server" and ansible_facts.distribution == "Alpine"
        block:
        - apk:
            name: "{{item}}"
          loop:
            - mc
            - tmux
      - when: purpose == "server" and ansible_facts.distribution == "Debian"
        block:
        - apt:
            name: "{{item}}"
          loop:
            - mc
            - tmux
      - when: purpose == "desktop"
        block:
        - include_role: name=desktop_apt_install
