---
- name: Update/Upgrade
  hosts: all
  gather_facts: true
  tasks:
  - group_by:
      key: OS_{{ansible_facts.distribution}}

- hosts: OS_Debian
  become: true
  tasks:
  - apt:
      update_cache: yes
      upgrade: yes
      autoremove: yes
      clean: yes
    register: r
  - debug:
      msg: "{{r.stdout}}"

- hosts: OS_Alpine
  become: true
  tasks:
  - apk:
      update_cache: true
      upgrade: true
    register: r
  - debug:
      msg: "{{r.stdout}}"