{
 "title": "Home",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "🌡",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "max(node_hwmon_temp_celsius{instance=\"atom\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(node_hwmon_temp_celsius{instance=\"tw89\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(node_thermal_zone_temp{instance=\"a1\"})",
     "legendFormat": "__auto"
    },
    { "expr": "manual_temp_celcius", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HDD",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "node_filesystem_avail_bytes", "legendFormat": "__auto" },
    { "expr": "manual_filesystem_avail_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "__auto" },
    { "expr": "manual_memory_avail_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds",
     "legendFormat": "__auto"
    },
    { "expr": "manual_uptime", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "LA",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "node_load1", "legendFormat": "__auto" },
    { "expr": "manual_load_avg1", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "cp19",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "success", "legendFormat": "__auto" },
    { "expr": "cppcheck", "legendFormat": "__auto" },
    { "expr": "shellcheck", "legendFormat": "__auto" },
    { "expr": "pylint", "legendFormat": "__auto" },
    { "expr": "duration_job_total", "legendFormat": "__auto" }
   ]
  }
 ]
}