---
### GRAFANA ####################################################################
apiVersion: v1
kind: Namespace
metadata:
  name: my-grafana
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: my-grafana
  name: etc-configmap
data:
  # Сменить Viewer на Admin чтобы что-то добавить.
  grafana.ini: |-
    [server]
    root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/
    serve_from_sub_path = true
    [paths]
    provisioning = /etc/grafana/provisioning
    [users]
    allow_sign_up    = false
    allow_org_create = false
    viewers_can_edit = true
    editors_can_admin = true
    [auth]
    disable_login_form = true
    [auth.basic]
    enabled = false
    [auth.anonymous]
    enabled = true
    org_role = Viewer
    [analytics]
    reporting_enabled = false
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: my-grafana
  name: datasources-configmap
data:
  default.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-svc.my-prometheus:9090/prometheus
      isDefault: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: my-grafana
  name: dashboards-configmap
data:
  home.json: |-
    {"annotations":{"list":[{"builtIn":1,"datasource":{"type":"grafana","uid":"-- Grafana --"},"enable":true,"hide":true,"iconColor":"rgba(0, 211, 255, 1)","name":"Annotations & Alerts","target":{"limit":100,"matchAny":false,"tags":[],"type":"dashboard"},"type":"dashboard"}]},"editable":true,"fiscalYearStartMonth":0,"graphTooltip":0,"links":[],"liveNow":false,"panels":[{"datasource":{"type":"prometheus","uid":"PBFA97CFB590B2093"},"fieldConfig":{"defaults":{"color":{"mode":"fixed"},"custom":{"axisCenteredZero":false,"axisColorMode":"text","axisLabel":"","axisPlacement":"auto","barAlignment":0,"drawStyle":"line","fillOpacity":0,"gradientMode":"none","hideFrom":{"legend":false,"tooltip":false,"viz":false},"lineInterpolation":"linear","lineWidth":1,"pointSize":5,"scaleDistribution":{"log":2,"type":"log"},"showPoints":"auto","spanNulls":false,"stacking":{"group":"A","mode":"none"},"thresholdsStyle":{"mode":"off"}},"mappings":[],"thresholds":{"mode":"absolute","steps":[{"color":"green","value":null},{"color":"red","value":80}]},"unit":"celsius"},"overrides":[{"matcher":{"id":"byName","options":"max(node_thermal_zone_temp{instance=\"a1\"})"},"properties":[{"id":"color","value":{"fixedColor":"red","mode":"fixed"}}]},{"matcher":{"id":"byName","options":"max(node_hwmon_temp_celsius{instance=\"atom\"})"},"properties":[{"id":"color","value":{"fixedColor":"green","mode":"fixed"}}]},{"matcher":{"id":"byName","options":"max(node_hwmon_temp_celsius{instance=\"tw89\"})"},"properties":[{"id":"color","value":{"fixedColor":"blue","mode":"fixed"}}]}]},"gridPos":{"h":8,"w":12,"x":0,"y":0},"id":123127,"options":{"legend":{"calcs":[],"displayMode":"list","placement":"bottom","showLegend":false},"tooltip":{"mode":"single","sort":"none"}},"targets":[{"datasource":{"type":"prometheus","uid":"PBFA97CFB590B2093"},"editorMode":"builder","expr":"max(node_hwmon_temp_celsius{instance=\"atom\"})","legendFormat":"__auto","range":true,"refId":"A"},{"datasource":{"type":"prometheus","uid":"PBFA97CFB590B2093"},"editorMode":"builder","expr":"max(node_hwmon_temp_celsius{instance=\"tw89\"})","hide":false,"legendFormat":"__auto","range":true,"refId":"B"},{"datasource":{"type":"prometheus","uid":"PBFA97CFB590B2093"},"editorMode":"builder","expr":"max(node_thermal_zone_temp{instance=\"a1\"})","hide":false,"legendFormat":"__auto","range":true,"refId":"C"},{"datasource":{"type":"prometheus","uid":"PBFA97CFB590B2093"},"editorMode":"code","expr":"manual_temp_celcius","hide":false,"legendFormat":"__auto","range":true,"refId":"D"}],"title":"🌡","type":"timeseries"},{"datasource":{"type":"prometheus","uid":"PBFA97CFB590B2093"},"fieldConfig":{"defaults":{"color":{"mode":"fixed"},"custom":{"axisCenteredZero":false,"axisColorMode":"text","axisLabel":"","axisPlacement":"auto","barAlignment":0,"drawStyle":"line","fillOpacity":0,"gradientMode":"none","hideFrom":{"legend":false,"tooltip":false,"viz":false},"lineInterpolation":"linear","lineStyle":{"fill":"solid"},"lineWidth":1,"pointSize":5,"scaleDistribution":{"log":2,"type":"log"},"showPoints":"auto","spanNulls":false,"stacking":{"group":"A","mode":"none"},"thresholdsStyle":{"mode":"off"}},"mappings":[],"thresholds":{"mode":"absolute","steps":[{"color":"green","value":null},{"color":"red","value":80}]},"unit":"decbytes"},"overrides":[{"matcher":{"id":"byRegexp","options":".*a1.*"},"properties":[{"id":"color","value":{"fixedColor":"red","mode":"fixed"}}]},{"matcher":{"id":"byRegexp","options":".*tw89.*"},"properties":[{"id":"color","value":{"fixedColor":"blue","mode":"fixed"}}]},{"matcher":{"id":"byRegexp","options":".*atom.*"},"properties":[{"id":"color","value":{"fixedColor":"green","mode":"fixed"}}]}]},"gridPos":{"h":8,"w":12,"x":12,"y":0},"id":123129,"options":{"legend":{"calcs":[],"displayMode":"list","placement":"bottom","showLegend":false},"tooltip":{"mode":"single","sort":"none"}},"targets":[{"datasource":{"type":"prometheus","uid":"PBFA97CFB590B2093"},"editorMode":"builder","expr":"node_filesystem_avail_bytes","legendFormat":"__auto","range":true,"refId":"A"},{"datasource":{"type":"prometheus","uid":"PBFA97CFB590B2093"},"editorMode":"code","expr":"manual_filesystem_avail_bytes","hide":false,"legendFormat":"__auto","range":true,"refId":"B"}],"title":"HDD","type":"timeseries"},{"datasource":{"type":"prometheus","uid":"PBFA97CFB590B2093"},"fieldConfig":{"defaults":{"color":{"mode":"fixed"},"custom":{"axisCenteredZero":false,"axisColorMode":"text","axisLabel":"","axisPlacement":"auto","barAlignment":0,"drawStyle":"line","fillOpacity":0,"gradientMode":"none","hideFrom":{"legend":false,"tooltip":false,"viz":false},"lineInterpolation":"linear","lineWidth":1,"pointSize":5,"scaleDistribution":{"log":2,"type":"log"},"showPoints":"auto","spanNulls":false,"stacking":{"group":"A","mode":"none"},"thresholdsStyle":{"mode":"off"}},"mappings":[],"thresholds":{"mode":"absolute","steps":[{"color":"green","value":null},{"color":"red","value":80}]},"unit":"decbytes"},"overrides":[{"matcher":{"id":"byName","options":"{__name__=\"node_memory_MemAvailable_bytes\", instance=\"a1\", job=\"node-exporter\"}"},"properties":[{"id":"color","value":{"fixedColor":"red","mode":"fixed"}}]},{"matcher":{"id":"byName","options":"{__name__=\"node_memory_MemAvailable_bytes\", instance=\"atom\", job=\"node-exporter\"}"},"properties":[{"id":"color","value":{"fixedColor":"green","mode":"fixed"}}]},{"matcher":{"id":"byName","options":"{__name__=\"node_memory_MemAvailable_bytes\", instance=\"tw89\", job=\"node-exporter\"}"},"properties":[{"id":"color","value":{"fixedColor":"blue","mode":"fixed"}}]}]},"gridPos":{"h":8,"w":12,"x":0,"y":8},"id":123131,"options":{"legend":{"calcs":[],"displayMode":"list","placement":"bottom","showLegend":false},"tooltip":{"mode":"single","sort":"none"}},"targets":[{"datasource":{"type":"prometheus","uid":"PBFA97CFB590B2093"},"editorMode":"builder","expr":"node_memory_MemAvailable_bytes","legendFormat":"__auto","range":true,"refId":"A"},{"datasource":{"type":"prometheus","uid":"PBFA97CFB590B2093"},"editorMode":"code","expr":"manual_memory_avail_bytes","hide":false,"legendFormat":"__auto","range":true,"refId":"B"}],"title":"RAM","type":"timeseries"},{"datasource":{"type":"prometheus","uid":"PBFA97CFB590B2093"},"fieldConfig":{"defaults":{"color":{"mode":"fixed"},"custom":{"axisCenteredZero":false,"axisColorMode":"text","axisLabel":"","axisPlacement":"auto","barAlignment":0,"drawStyle":"line","fillOpacity":0,"gradientMode":"none","hideFrom":{"legend":false,"tooltip":false,"viz":false},"lineInterpolation":"linear","lineWidth":1,"pointSize":5,"scaleDistribution":{"log":2,"type":"log"},"showPoints":"auto","spanNulls":false,"stacking":{"group":"A","mode":"none"},"thresholdsStyle":{"mode":"off"}},"mappings":[],"thresholds":{"mode":"absolute","steps":[{"color":"green","value":null},{"color":"red","value":80}]},"unit":"s"},"overrides":[{"matcher":{"id":"byName","options":"{instance=\"a1\", job=\"node-exporter\"}"},"properties":[{"id":"color","value":{"fixedColor":"red","mode":"fixed"}}]},{"matcher":{"id":"byName","options":"{instance=\"atom\", job=\"node-exporter\"}"},"properties":[{"id":"color","value":{"fixedColor":"green","mode":"fixed"}}]},{"matcher":{"id":"byName","options":"{instance=\"tw89\", job=\"node-exporter\"}"},"properties":[{"id":"color","value":{"fixedColor":"blue","mode":"fixed"}}]}]},"gridPos":{"h":8,"w":12,"x":12,"y":8},"id":123135,"options":{"legend":{"calcs":[],"displayMode":"list","placement":"bottom","showLegend":false},"tooltip":{"mode":"single","sort":"none"}},"targets":[{"datasource":{"type":"prometheus","uid":"PBFA97CFB590B2093"},"editorMode":"code","expr":"node_time_seconds - node_boot_time_seconds","hide":false,"legendFormat":"__auto","range":true,"refId":"A"},{"datasource":{"type":"prometheus","uid":"PBFA97CFB590B2093"},"editorMode":"code","expr":"manual_uptime","hide":false,"legendFormat":"__auto","range":true,"refId":"B"}],"title":"Uptime","transformations":[],"type":"timeseries"},{"datasource":{"type":"prometheus","uid":"PBFA97CFB590B2093"},"fieldConfig":{"defaults":{"color":{"mode":"fixed"},"custom":{"axisCenteredZero":false,"axisColorMode":"text","axisLabel":"","axisPlacement":"auto","barAlignment":0,"drawStyle":"line","fillOpacity":0,"gradientMode":"none","hideFrom":{"legend":false,"tooltip":false,"viz":false},"lineInterpolation":"linear","lineWidth":1,"pointSize":5,"scaleDistribution":{"type":"linear"},"showPoints":"auto","spanNulls":false,"stacking":{"group":"A","mode":"none"},"thresholdsStyle":{"mode":"off"}},"mappings":[],"thresholds":{"mode":"absolute","steps":[{"color":"green","value":null},{"color":"red","value":80}]}},"overrides":[{"matcher":{"id":"byName","options":"{__name__=\"node_load1\", instance=\"a1\", job=\"node-exporter\"}"},"properties":[{"id":"color","value":{"fixedColor":"red","mode":"fixed"}}]},{"matcher":{"id":"byName","options":"{__name__=\"node_load1\", instance=\"atom\", job=\"node-exporter\"}"},"properties":[{"id":"color","value":{"fixedColor":"green","mode":"fixed"}}]},{"matcher":{"id":"byName","options":"{__name__=\"node_load1\", instance=\"tw89\", job=\"node-exporter\"}"},"properties":[{"id":"color","value":{"fixedColor":"blue","mode":"fixed"}}]}]},"gridPos":{"h":8,"w":12,"x":0,"y":16},"id":123133,"options":{"legend":{"calcs":[],"displayMode":"list","placement":"bottom","showLegend":false},"tooltip":{"mode":"single","sort":"none"}},"targets":[{"datasource":{"type":"prometheus","uid":"PBFA97CFB590B2093"},"editorMode":"builder","expr":"node_load1","legendFormat":"__auto","range":true,"refId":"A"},{"datasource":{"type":"prometheus","uid":"PBFA97CFB590B2093"},"editorMode":"code","expr":"manual_load_avg1","hide":false,"legendFormat":"__auto","range":true,"refId":"B"}],"title":"LA","type":"timeseries"},{"datasource":{"type":"prometheus","uid":"PBFA97CFB590B2093"},"fieldConfig":{"defaults":{"color":{"fixedColor":"orange","mode":"fixed","seriesBy":"last"},"custom":{"axisCenteredZero":false,"axisColorMode":"series","axisLabel":"","axisPlacement":"auto","barAlignment":0,"drawStyle":"line","fillOpacity":0,"gradientMode":"none","hideFrom":{"legend":false,"tooltip":false,"viz":false},"lineInterpolation":"stepAfter","lineStyle":{"fill":"solid"},"lineWidth":1,"pointSize":5,"scaleDistribution":{"log":2,"type":"log"},"showPoints":"auto","spanNulls":false,"stacking":{"group":"A","mode":"none"},"thresholdsStyle":{"mode":"off"}},"mappings":[],"thresholds":{"mode":"absolute","steps":[{"color":"green","value":null},{"color":"red","value":80}]},"unit":"none"},"overrides":[{"matcher":{"id":"byName","options":"{__name__=\"duration_job_total\", exported_job=\"cp19\", instance=\"pushgateway-svc:9091\", job=\"pushgateway\", pushgateway_instance=\"metricfire\"}"},"properties":[{"id":"unit","value":"ms"},{"id":"color","value":{"fixedColor":"text","mode":"fixed"}},{"id":"custom.axisPlacement","value":"right"}]},{"matcher":{"id":"byName","options":"{__name__=\"success\", exported_job=\"cp19\", instance=\"pushgateway-svc:9091\", job=\"pushgateway\", pushgateway_instance=\"metricfire\"}"},"properties":[{"id":"color","value":{"fixedColor":"green","mode":"fixed"}},{"id":"custom.axisPlacement","value":"hidden"},{"id":"custom.fillOpacity","value":50},{"id":"custom.lineWidth","value":0},{"id":"max","value":1}]},{"matcher":{"id":"byName","options":"failure"},"properties":[{"id":"custom.axisPlacement","value":"hidden"},{"id":"max","value":1},{"id":"custom.fillOpacity","value":50},{"id":"custom.lineWidth","value":0},{"id":"color","value":{"fixedColor":"red","mode":"fixed"}}]}]},"gridPos":{"h":8,"w":12,"x":12,"y":16},"id":123125,"options":{"legend":{"calcs":[],"displayMode":"list","placement":"bottom","showLegend":false},"tooltip":{"mode":"single","sort":"none"}},"pluginVersion":"9.1.0","targets":[{"datasource":{"type":"prometheus","uid":"PBFA97CFB590B2093"},"editorMode":"code","expr":"success","hide":false,"legendFormat":"__auto","range":true,"refId":"E"},{"datasource":{"type":"prometheus","uid":"PBFA97CFB590B2093"},"editorMode":"builder","expr":"cppcheck","legendFormat":"__auto","range":true,"refId":"A"},{"datasource":{"type":"prometheus","uid":"PBFA97CFB590B2093"},"editorMode":"builder","expr":"shellcheck","hide":false,"legendFormat":"__auto","range":true,"refId":"B"},{"datasource":{"type":"prometheus","uid":"PBFA97CFB590B2093"},"editorMode":"builder","expr":"pylint","hide":false,"legendFormat":"__auto","range":true,"refId":"C"},{"datasource":{"type":"prometheus","uid":"PBFA97CFB590B2093"},"editorMode":"builder","expr":"duration_job_total","hide":false,"legendFormat":"__auto","range":true,"refId":"D"}],"title":"cp19","transformations":[{"id":"calculateField","options":{"alias":"failure","binary":{"left":"1","operator":"-","reducer":"sum","right":"{__name__=\"success\", exported_job=\"cp19\", instance=\"pushgateway-svc:9091\", job=\"pushgateway\", pushgateway_instance=\"metricfire\"}"},"mode":"binary","reduce":{"reducer":"sum"}}}],"transparent":true,"type":"timeseries"}],"refresh":false,"schemaVersion":37,"style":"dark","tags":[],"templating":{"list":[]},"time":{"from":"now-1h","to":"now"},"timepicker":{"hidden":false,"refresh_intervals":["5s","10s","30s","1m","5m","15m","30m","1h","2h","1d"],"time_options":["5m","15m","1h","6h","12h","24h","2d","7d","30d"],"type":"timepicker"},"timezone":"browser","title":"Home","version":0,"weekStart":""}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: my-grafana
  name: grafana-app
spec:
  selector:
    matchLabels:
      name: grafana-app
  template:
    metadata:
      labels:
        name: grafana-app
    spec:
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
        - name: grafana
          image: grafana/grafana:9.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http-grafana
              protocol: TCP
          # readinessProbe:
          #   failureThreshold: 3
          #   httpGet:
          #     path: /robots.txt
          #     port: 3000
          #     scheme: HTTP
          #   initialDelaySeconds: 10
          #   periodSeconds: 30
          #   successThreshold: 1
          #   timeoutSeconds: 2
          # livenessProbe:
          #   failureThreshold: 3
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          #   successThreshold: 1
          #   tcpSocket:
          #     port: 3000
          #   timeoutSeconds: 1
          # resources:
          #   requests:
          #     cpu: 250m
          #     memory: 750Mi
          volumeMounts:
            - name: etc
              mountPath: /etc/grafana
            - name: datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: dashboards
              mountPath: /usr/share/grafana/public/dashboards
      volumes:
      - name: etc
        configMap:
          defaultMode: 420
          name: etc-configmap
      - name: datasources
        configMap:
          defaultMode: 420
          name: datasources-configmap
      - name: dashboards
        configMap:
          defaultMode: 420
          name: dashboards-configmap
---
apiVersion: v1
kind: Service
metadata:
  namespace: my-grafana
  name: grafana-svc
spec:
  selector:
    name: grafana-app
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: http-grafana
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: my-grafana
  name: grafana-ingress
spec:
  rules:
  - http:
      paths:
      - path: /grafana
        pathType: Prefix
        backend:
          service:
            name: grafana-svc
            port:
              number: 3000
